name: Post merge workflow
on:
  push:
    branches:
      - develop
      - release/*
jobs:
  app-build:
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
          password: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}
      - name: Pack the application bundle
        id: pack
        env:
          DOCKER_ORG: entando
        run: |
          versionSuffix=SNAPSHOT
          bash ./.github/functions/utils.sh setBundleVersion -$versionSuffix
          bash ./.github/functions/utils.sh setComponentVersions -$versionSuffix
          ent --debug bundle pack --org $DOCKER_ORG --stdout --fail-fast
          ent --debug bundle publish
          version=$(bash ./.github/functions/utils.sh getBundleImage)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
        working-directory: ./