name: Release
on:
  create:
    tags:
      - 'v*'
jobs:
  app-build:
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
          password: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}
      - name: Get release tag
        id: release
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Pack the application bundle
        id: pack
        env:
          DOCKER_ORG: entando
          RELEASE_VERSION: ${{ steps.release.outputs.tag }}
        run: |
          bash ../.github/functions/utils.sh setBundleVersionTag ${RELEASE_VERSION#v}
          bash ../.github/functions/utils.sh setComponentVersionsTag ${RELEASE_VERSION#v}
          ent --debug bundle pack --org $DOCKER_ORG --stdout --fail-fast
          ent --debug bundle publish
          version=$(bash ../.github/functions/utils.sh getBundleImage)
          echo "VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT
        working-directory: ./